function InputPlusH = RobotDynamicMatrixH(Input,m,r,l,ycm,xcm,Icm)
%ROBOTDYNAMICMATRIXH
%    INPUTPLUSH = ROBOTDYNAMICMATRIXH(INPUT,M,R,L,YCM,XCM,ICM)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    07-May-2019 23:41:05

t2 = sqrt(2.0);
t3 = 1.0./l.^2;
t4 = r.^2;
t5 = xcm.^2;
t6 = m.*t5;
t7 = ycm.^2;
t8 = m.*t7;
t9 = l.*m.*t2.*ycm.*2.0;
t10 = l.^2;
t11 = m.*t10.*4.0;
t12 = l.*m.*t2.*xcm.*2.0;
t13 = Icm+t6+t8+t9;
t14 = t3.*t4.*t13.*(1.0./1.6e1);
t15 = Input+t14;
t16 = Icm+t6+t8-t11;
t17 = t3.*t4.*t16.*(1.0./1.6e1);
t18 = Input+t17;
t19 = Icm+t6+t8-t12;
t20 = t3.*t4.*t19.*(1.0./1.6e1);
t21 = Input+t20;
t22 = Icm+t6+t8+t12;
t23 = t3.*t4.*t22.*(1.0./1.6e1);
t24 = Input+t23;
t25 = Icm+t6+t8-t9;
t26 = t3.*t4.*t25.*(1.0./1.6e1);
t27 = Input+t26;
InputPlusH = reshape([Input+t3.*t4.*(Icm+t6+t8+t9+t11+t12).*(1.0./1.6e1),t15,t18,t24,t15,Input+t3.*t4.*(Icm+t6+t8+t9+t11-t12).*(1.0./1.6e1),t21,t18,t18,t21,Input+t3.*t4.*(Icm+t6+t8-t9+t11-t12).*(1.0./1.6e1),t27,t24,t18,t27,Input+t3.*t4.*(Icm+t6+t8-t9+t11+t12).*(1.0./1.6e1)],[4,4]);
