function InputPlusH = RobotDynamicMatrixH(Input,m,r,l,ycm,xcm,Icm)
%ROBOTDYNAMICMATRIXH
%    INPUTPLUSH = ROBOTDYNAMICMATRIXH(INPUT,M,R,L,YCM,XCM,ICM)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    08-May-2019 10:16:31

t2 = sqrt(2.0);
t3 = 1.0./l.^2;
t4 = r.^2;
t5 = xcm.^2;
t6 = m.*t5;
t7 = ycm.^2;
t8 = m.*t7;
t9 = l.*m.*t2.*ycm.*2.0;
t10 = l.^2;
t11 = m.*t10.*4.0;
t12 = l.*m.*t2.*xcm.*2.0;
t13 = Icm+t6+t8+t9;
t14 = t3.*t4.*t13.*(1.0./1.6e1);
t15 = Icm+t6+t8-t11;
t16 = t3.*t4.*t15.*(1.0./1.6e1);
t17 = Icm+t6+t8-t12;
t18 = t3.*t4.*t17.*(1.0./1.6e1);
t19 = Icm+t6+t8+t12;
t20 = t3.*t4.*t19.*(1.0./1.6e1);
t21 = Icm+t6+t8-t9;
t22 = t3.*t4.*t21.*(1.0./1.6e1);
InputPlusH = reshape([t3.*t4.*(Icm+t6+t8+t9+t11+t12).*(1.0./1.6e1),t14,t16,t20,t14,t3.*t4.*(Icm+t6+t8+t9+t11-t12).*(1.0./1.6e1),t18,t16,t16,t18,t3.*t4.*(Icm+t6+t8-t9+t11-t12).*(1.0./1.6e1),t22,t20,t16,t22,t3.*t4.*(Icm+t6+t8-t9+t11+t12).*(1.0./1.6e1)],[4,4]);
InputPlusH = (InputPlusH + Input);